spring.application.name=financeapp
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Définir le niveau de logs de l’application
logging.level.root=INFO
logging.level.com.finanzmanager=DEBUG

# Enregistrer dans un fichier (optionnel)
logging.file.name=logs/finanzapp.log

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

#Custom Port (8081 au lieu de 8080)
server.port=8081

