spring.application.name=financeapp
spring.profiles.active=dev

# Proprietés personnalisées de l'application
app.name=FinanceApp
app.default-currency=EUR
app.max-transactions=500

#Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=com.financemanager.financeapp.controller

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


