spring.application.name=financeapp
spring.profiles.active=dev

# Proprietés personnalisées de l'application
app.name=FinanceApp
app.default-currency=EUR
app.max-transactions=500

#Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=com.financemanager.financeapp.controller

#JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

#Infos endpoint
info.app.name = FinanceApp
info.app.version=0.0.1
info.app.currency=EUR
info.app.max-transactions=500
